global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'foilctf'
    environment: 'production'

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['gateway:443']
    metrics_path: '/metrics'